// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQvzLJgPcJViiyNcbgA9zWUk-rJDDTWY',
    appId: '1:330611276940:web:008feb13e3dbe033938fa9',
    messagingSenderId: '330611276940',
    projectId: 'task-27787',
    authDomain: 'task-27787.firebaseapp.com',
    storageBucket: 'task-27787.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh7VywEmTNnkR9_0ShBBmRaMMoSC7HHoM',
    appId: '1:330611276940:android:ceec65f1d0a39e4c938fa9',
    messagingSenderId: '330611276940',
    projectId: 'task-27787',
    storageBucket: 'task-27787.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqreewFHX6kxlHippOSezExEWBYwSC_8',
    appId: '1:330611276940:ios:2b738b43d2966b38938fa9',
    messagingSenderId: '330611276940',
    projectId: 'task-27787',
    storageBucket: 'task-27787.appspot.com',
    iosBundleId: 'com.example.task',
  );
}
